name: test
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    name: Test code
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

        go-version:
          - stable
          - "" # empty string = read version from go.mod

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      ARTIFACT_TEST: "wheel-test_result-go_${{ matrix.go-version }}-${{ matrix.os }}.json"
    steps:
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: "0"
          submodules: recursive

      - name: Test wheel
        run: |
          nix develop --command bash -c "
            echo "test.yaml: Starting test"
            go test -race -count=1 -p=1 -json ./... | tee $ARTIFACT_TEST
          ";

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: test_result-go${{ matrix.go-version }}_${{ matrix.os }}
          path: ${{ env.ARTIFACT_TEST }}
